config/routes.rb
Rails.application.routes.draw do
  get '/', to: "quizzes#index"

  #TODO
  resources :quizzes

  namespace :editor do
    ##### export/import #####
    get 'quizzes/:uuid/export', to: 'quizzes#export'
    get 'quizzes/import', to: 'quizzes#import_page'
    post 'quizzes/import', to: 'quizzes#import'

    ##### quizzes ######
    get 'quizzes', to: 'quizzes#index'
    get 'quizzes/new', to: 'quizzes#new'
    post 'quizzes', to: 'quizzes#create'
    get 'quizzes/:uuid', to: 'quizzes#show'
    get 'quizzes/:uuid/edit', to: 'quizzes#edit'
    put 'quizzes/:uuid', to: 'quizzes#update'
    delete 'quizzes/:uuid', to: 'quizzes#destroy'

    ##### questions #####
    get 'quizzes/:uuid/q/new', to: 'questions#new'
    post 'quizzes/:uuid/q', to: 'questions#create'
    get 'quizzes/:uuid/q/:q', to: 'questions#edit'
    put 'quizzes/:uuid/q/:q', to: 'questions#update'
    delete 'quizzes/:uuid/q/:q', to: 'questions#destroy'

    ##### answers #####
    post 'q/:id/answers', to: 'answers#create'
    put 'answers/:id', to: 'answers#update'
    delete 'answers/:id', to: 'answers#destroy'
  end

  get 'email_confirmation', to: 'users#email_confirmation'
  post 'email_confirmation', to: 'users#check_email'
  get 'send_token', to: 'users#send_email'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  post 'users/:id/switch_admin', to: 'users#switch_admin'
  resources :users, except: [:new]

  get 'email', to: 'sessions#email'

  get ':uuid', to: 'quizzes#connect'
  get ':uuid/certificate', to: 'quizzes#certificate'
  get ':uuid/results', to: 'quizzes#results'
  get ':uuid/:q', to: 'quizzes#question'
  post ':uuid/:q', to: 'quizzes#send_answer' 
end

app/controllers/api/quizzes_controller.rb
class Api::QuizzesController < ApplicationController
  def index
    render :json => Quiz.all
  end

  def new
    user = User.find_by(:id => params[:id])
    quiz = user.authored_quizzes.create!(:title => params[:title], :description => params[:description])
    render :json => quiz
  end

  def show
    quiz = Quiz.find_by(:uuid => params[:uuid])
    render :json => {quiz: quiz, questions_count: quiz.questions.count}
  end

  def author
    render :json => Quiz.find_by(:uuid => params[:uuid]).author
  end

  def update
    quiz = Quiz.find_by(:uuid => params[:uuid])
    quiz.update!(:description => params[:description]) if params[:description]
    quiz.update!(:title => params[:title]) if params[:title]
    render :json => quiz
  end

  def destroy
    quiz = Quiz.find_by(:uuid => params[:uuid])
    quiz.destroy!
    render :json => {'message' => 'Deleted'}
  end
end

app/controllers/editor/quizzes_controller.rb
class Editor::QuizzesController < ApplicationController
  def index 
    if $user.admin
      @quizzes = Quiz.all
    else
      @quizzes = Quiz.where(:author_id => $user.id)
    end
  rescue => e
    flash[:notice] = e.message
  end

  def new
  
  rescue => e
    flash[:notice] = e.message
  end

  def create
    quiz = Quiz.create!(
      params[:quiz].permit(
        :title,
        :description
      ).merge(:author_id => $user.id)
    )
    redirect_to "/editor/quizzes/#{quiz.uuid}"
  rescue => e
    flash[:notice] = e.message
  end

  def show
    @quiz = Quiz.find_by(:uuid => params[:uuid])
    @questions = @quiz.questions
  rescue => e
    flash[:notice] = e.message
  end
  
  def edit
    @quiz = Quiz.find_by(:uuid => params[:uuid])
  rescue => e
    flash[:notice] = e.message
  end

  def update
    quiz = Quiz.find_by(:uuid => params[:uuid])
    quiz.update!(
      params[:quiz].permit(
        :title,
        :description,
        :author_id
      )
    )
    redirect_to "/editor/quizzes/#{quiz.uuid}"
  rescue => e
    flash[:notice] = e.message
  end

  def destroy
    Quiz.find_by(:uuid => params[:uuid]).destroy!
    redirect_to "/editor/quizzes"
  rescue => e
    flash[:notice] = e.message
  end

  def export
    quiz = Quiz.find_by(:uuid => params[:uuid])
    questions = quiz.questions.map do |question|
      answers = question.answers.map do |answer|
        answer.attributes.except("id", "created_at", "updated_at", "question_id")
      end
      question.attributes.
        except("id", "time", "created_at", "updated_at", "quiz_id").
        merge(:answers => answers)
    end
    file = File.new("quiz.json", "w+")
    file.print(
      quiz.attributes.
      except("id", "uuid", "created_at", "updated_at", "author_id").
      merge(:questions => questions).to_json    
    )
    file.close
    send_file "quiz.json", :type => 'application/json'
  rescue => e
    flash[:notice] = e.message
  end

  def import_page

  rescue => e
    flash[:notice] = e.message
  end

  def import
    unless params[:quiz]
      flash[:notice] = "Invalid file"
      return redirect_to '/editor/quizzes/import'
    end
    unless params[:quiz][:file]
      flash[:notice] = "Invalid file"
      return redirect_to '/editor/quizzes/import'
    end
    unless params[:quiz][:file].content_type == 'application/json'
      flash[:notice] = "Invalid file"
      return redirect_to '/editor/quizzes/import'
    end
    data = JSON.parse(params[:quiz][:file].read)
    quiz = Quiz.new(
      :description => data["description"],
      :title => data["title"],
      :author_id => $user.id
    )
    data["questions"].each do |question|
      q = quiz.questions.new(
        :points => question["points"],
        :text => question["text"],
        :question_type => question["question_type"]
      )
      question["answers"].each do |answer|
        q.answers.new(
          :text => answer["text"],
          :right => answer["right"]
        )
      end
    end
    quiz.save!
    redirect_to "/editor/quizzes/#{quiz.uuid}"
  rescue => e
    flash[:notice] = e.message
    redirect_to "/editor/quizzes/import"
  end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  #require Responce

  def index
    @quizzes = Quiz.all
  rescue => e
    flash[:notice] = e.message
  end

  def new

  rescue => e
    flash[:notice] = e.message
  end

  def show
    @quiz = Quiz.find(params[:id])
    @questions = @quiz.questions
  rescue => e
    flash[:notice] = e.message
  end

  def create
    user = User.last
    quiz = user.authored_quizzes.create!(
      params[:quiz].permit(
        :title,
        :description
      )
    )
    redirect_to quiz
  rescue => e
    flash[:notice] = e.message
  end

  def connect
    unless quiz = Quiz.find_by(:uuid => params[:uuid])
      return render :plain => "404, Not found", :status => :not_found
    end
    unless $user
      return render :json => {:message => "You're not authorized"}
    end
    unless quiz.users.find_by(:id => $user.id)
      quiz.users << $user
    end
    quiz.participants.find_by(:user_id => $user.id).update!(:score => 0)
    redirect_to "/#{params[:uuid]}/0"
  rescue => e
    flash[:notice] = e.message
  end

  def question
    unless @quiz = Quiz.find_by(:uuid => params[:uuid])
      return render :plain => "404, Quiz not found", :status => :not_found
    end
    unless @question = @quiz.questions[params[:q].to_i]
      return render :plain => "404, Question not found", :status => :not_found
    end
    @answers = @question.answers.shuffle
  rescue => e
    flash[:notice] = e.message
  end

  def send_answer
    unless quiz = Quiz.find_by(:uuid => params[:uuid])
      return render :json => {'message' => 'Quiz not found'}
    end
    unless $user
      return render :json => {:message => 'You\'re not authorized'}
    end
    unless quiz.users.find_by(:id => $user.id)
      redirect_to "/#{params[:uuid]}"
    else
      participant = quiz.participants.find_by(:user_id => $user.id, :quiz_id => quiz.id)
    end
    unless @q = quiz.questions[params[:q].to_i]
      return render :json => {'message' => 'Question not found'}
    end
    @outp = {}
    p 'DEBUG'
    p @q.question_type
    case @q.question_type
    when 'Multiple choice'
      @outp[:right_answer] = @q.answers.find_by(:right => true).text
      if Answer.find_by(:id => params[:answer][:ans].to_i).right
        @outp[:result] = 'right'
        participant.score += @q.points
        @outp[:points] = @q.points
      else
        @outp[:result] = 'wrong'
        @outp[:points] = 0
      end
    when 'Fill in the blank'
      @outp[:right_answer] = @q.answers.find_by(:right => true).text
      if @q.answers.find_by(:text => params[:answer][:ans])
        @outp[:result] = 'right'
        participant.score += @q.points
        @outp[:points] = @q.points
      else
        @outp[:result] = 'wrong'
        @outp[:points] = 0
      end
    when 'Multiple answer'
      p params[:answer]
      right = {}
      @q.answers.each do |e|
        if e.right
          right["#{e.id}"] = "1"
        else
          right["#{e.id}"] = "0"
        end
      end
      @outp[:right_answer] = right
      if params[:answer] == right
        @outp[:result] = 'right'
        participant.score += @q.points
        @outp[:points] = @q.points
      else
        @outp[:result] = 'wrong'
        @outp[:points] = 0
      end
    when 'True', 'False'
      @outp[:right_answer] = @q.question_type.to_bool
      if params[:answer][:ans].to_bool == @q.question_type.to_bool
        @outp[:result] = 'right'
        participant.score += @q.points
        @outp[:points] = @q.points
      else
        @outp[:result] = 'wrong'
        @outp[:points] = 0
      end
    when 'Numeric'
      if params[:answer][:ans].numeric?
        @outp[:right_answer] = @q.answers.first.text
        if params[:answer][:ans].to_f == @q.answers.first.text.to_f
          @outp[:result] = 'right'
          participant.score += @q.points
          @outp[:points] = @q.points
        else
          @outp[:result] = 'wrong'
          @outp[:points] = 0
        end
      else
        return render :json => {'message' => 'Answer should be numeric!'}
      end
    end
    if params[:q].to_i < quiz.questions.count - 1
      @outp[:next_question] = "#{params[:q].to_i + 1}"
    else
      @outp[:results_url] = true
    end
    participant.save
  rescue => e
    flash[:notice] = e.message
  end

  def results
    unless @quiz = Quiz.find_by(:uuid => params[:uuid])
      return render :json => {'message' => 'Quiz not found'}
    end
    unless $user
      return render :json => {:message => 'You\'re not authorized'}
    end
    unless @quiz.users.find_by(:id => $user.id)
      redirect_to "/#{params[:uuid]}"
    else
      @participant = @quiz.participants.find_by(:user_id => $user.id, :quiz_id => @quiz.id)
    end
    @max_score = 0
    @quiz.questions.each {|e| @max_score += e.points}
    @leaders = @quiz.participants.sort_by{|pt| 0 - pt.score}[0..9]
  rescue => e
    flash[:notice] = e.message
  end

  def certificate
    @quiz = Quiz.find_by(:uuid => params[:uuid])
    @participant = @quiz.participants.find_by(:user_id => $user.id)
    @time = @participant.updated_at.strftime("%d of %B, %Y")
    @max_score = 0
    @quiz.questions.each {|e| @max_score += e.points}

     render pdf: "Certificate",
                page_size: 'A5',
                template: "quizzes/certificate",
                layout: "pdf",
                orientation: "Landscape",
                lowquality: true,
                zoom: 1,
                dpi: 75
  rescue => e
    flash[:notice] = e.message
  end
end

app/helpers/editor/quizzes_helper.rb
module Editor::QuizzesHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/quizzes/index.html.erb
<h1>All our quizzes</h1>
<% @quizzes.each do |quiz| %>
  <h3><%= link_to "#{quiz.title}", "/quizzes/#{quiz.id}", :class => 'nav-link' %></h3>
  <p><%= quiz.description %></p><br>
<% end %>

app/views/quizzes/new.html.erb
<h2>Adding new quiz</h2>
<%= form_for :quiz, url: quizzes_path do |f| %>
  <p>
    Название<br>
    <%= f.text_field :title %>
  </p>
  <p>
    Описание<br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/quizzes/question.html.erb
<p>
  Question: <%= (params[:q].to_i + 1) %>/<%= @quiz.questions.count %><br>
  Points: <%= @question.points%><br>
</p>
<h2><%= @question.text %></h2>

<% case @question.question_type %>
<% when "True", "False" %>
  <p>True/False</p>
  <%= form_for :answer do |f| %>
    <div class="form-check">
      <%= f.radio_button :ans, "1", :class => 'form-check-input' %>
      <%= f.label :ans, "True", :class => 'form-check-label' %>
    </div>
    <div class="form-check">
      <%= f.radio_button :ans, "0", :class => 'form-check-input' %>
      <%= f.label :ans, "False", :class => 'form-checl-label' %>
    </div><br>
    <%= f.submit :class => 'btn btn-success' %>
  <% end %>

<% when "Multiple choice" %>
  <br>
  <%= form_for :answer do |f| %>
    <% @answers.each do |answer| %>
      <div class="form-check">
        <%= f.radio_button :ans, answer.id, :class => 'form-check-input' %>
        <%= f.label :ans, answer.text, :class => 'form-check-label' %>
      </div>
    <% end %>
    <br>
    <%= f.submit :class => 'btn btn-success' %>
  <% end %>

<% when "Fill in the blank" %>
  <p>Fill in the blank</p>
  <%= form_for :answer do |f| %>
    <p><%= f.text_field :ans, :class => 'form-control' %></p>
    <p><%= f.submit :class => 'btn btn-success' %></p>
  <% end %>

<% when "Multiple answer" %>
  <p>Multiple answer</p>
  <%= form_for :answer do |f| %>
    <p>
      <% @answers.each do |answer| %>
        <%= f.check_box :"#{answer.id}", :class => 'form-check-sm' %>
        <%= f.label :"#{answer.id}", "#{answer.text}", :class => 'form-label' %>
        <br>
      <% end %>
    </p>
    <p><%= f.submit :class => 'btn btn-success' %></p>
  <% end %>

<% when "Numeric" %>
  <p>Numeric</p>
  <%= form_for :answer do |f| %>
    <p><%= f.number_field :ans, :class => 'form-control' %></p>
    <p><%= f.submit :class => 'btn btn-success' %></p>
  <% end %>
<% end %>

app/views/quizzes/results.html.erb
<h1>Congratulations, you scored <%= @participant.score %> out of <%= @max_score %> points!</h1><br>
<h2>Leaders</h2>
<% @leaders.each do |pt| %>
  <% user = User.find_by(:id => pt.user_id) %>
  <p>
    <%= user.name %> - <%= pt.score %>
  </p>
<% end %>
<p>
  <%= link_to "Home", "/quizzes", :class => 'btn btn-primary' %>
  <%= link_to "Try again", "/#{@quiz.uuid}", :class => 'btn btn-warning' %>
  <%= link_to "Get certificate", "/#{@quiz.uuid}/certificate", :class => 'btn btn-success' %>
</p>

app/views/quizzes/send_answer.html.erb
<h2><%= @outp[:result].upcase %></h2><br>
<p>
  Right answer: 
  <% if @q.question_type == 'Multiple answer' %>
    <% @outp[:right_answer].select{|id, val| val == "1"}.keys.each do |answer| %>
      <br>• <%= @q.answers.find_by(:id => answer).text %>
    <% end %>
  <% else %>
    <br>• <%= @outp[:right_answer] %>
  <% end %>
  <br><br>
  Earned <%= @outp[:points] %> pt.
</p>
<% if @outp[:results_url] %>
  <%= link_to "View results", 'results', :class => 'btn btn-success' %>
<% elsif @outp[:next_question] %>
  <%= link_to "Next question", @outp[:next_question], :class => 'btn btn-success' %>
<% end %>

app/views/quizzes/show.html.erb
<h1><%= @quiz.title %></h1></li>
<% @quiz.attributes.except("id", "title", "author_id", "uuid", "created_at", "updated_at").merge(:author => User.find_by_id(@quiz.author_id).name).each do |attribute, value| %>
  <h4><%= attribute %></h4>
  <p><%= value %></p>
<% end %>
<p>Questions count: <%= @quiz.questions.count %></p>
<p>
  <%= link_to "Connect", "/#{@quiz.uuid}", :class => 'btn btn-primary' %>
  <%= link_to "Back", "/quizzes", :class => 'btn btn-warning' %>
</p>